function [prob] = GaussianPD(Data, Mu, Sigma)
%GaussianPD Likelihood of datapoint(s) to be generated by a Gaussian parameterized by center and covariance.
%   Data:  D x N array representing N datapoints of D dimensions.
%   Mu:    D x 1 vector representing the center of the Gaussian.
%   Sigma: D x D array representing the covariance matrix of the Gaussian.
%   prob:  1 x N vector representing the likelihood of the N datapoints.

%
% Copyright (c) 2015 Idiap Research Institute, http://idiap.ch/
% Written by Sylvain Calinon, http://calinon.ch/
% 
% This file is part of PbDlib, http://www.idiap.ch/software/pbdlib/
% 

[nbVar,nbData] = size(Data);
Data = Data' - repmat(Mu',nbData,1);
prob = sum((Data/Sigma).*Data, 2);
prob = exp(-0.5*prob) / sqrt((2*pi)^nbVar * abs(det(Sigma)) + realmin);

end

